language: node_js
sudo: required
addons:
  chrome: stable
node_js:
  - "node"
  - "9.3.0"
install:
  - npm install karma-cli
  - npm install
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: npm run test